### PR TITLE
Reorder track

### PR DESCRIPTION
**Pull request by stkent**
~~Waiting on https://github.com/exercism/discussions/issues/60#issuecomment-279096308 before I add difficulty scores to the individual `exercises`.~~

~~Should not be merged before #277.~~ #277 is now merged, so the track tests no longer use the `problems` key.

~~**Should not be merged before #292 is resolved.**~~ done!

Relates to https://github.com/exercism/xjava/issues/142, https://github.com/exercism/xjava/issues/125

### CODE REVIEW

**Comment by stkent** [comment]
Per other tracks that have made this change and assigned difficulties (e.g. https://github.com/exercism/xobjective-c/pull/125/files, https://github.com/exercism/xhaskell/pull/402/files, https://github.com/exercism/xfsharp/pull/198/files) I'll be rounding our computed average difficulties to integer values!

**Comment by stkent** [comment]
Once this PR is finalized and merged, I'll create separate issues for updating the difficulty score and track position for `clock` and `perfect-numbers`. After that any new exercises should probably propose both those attributes in the initial PR?

**Comment by stkent** [comment]
This is now ready for review!

**Comment by stkent** [comment]
This is paused again pending resolution of #292 :)

**Comment by jtigger** [comment]
Fun stats...

The following exercises held their positions:

- `hello-world`
- `triangle`
- `accumulate`
- `robot-simulator`
- `queen-attack`

The five exercises dropping in position the most:

- `secret-handshake` (-46 positions)
- `matrix` (-40 positions)
- `flatten-array` (-37 positions)
- `diamond` (-36 positions)
- `twelve-days` (-33 positions)

The five exercises climbing in position the most:

- `meetup` (+42 positions)
- `anagram` (+41 positions)
- `etl` (+38 positions)
- `crypto-square` (+28 positions)
- `simple-cipher` (+26 positions)

**Comment by stkent** [comment]
`grade-school` is now positioned in the middle of the sixes!

**Comment by stkent** [comment]
@jtigger I'm also v. excited about this step towards making the Java track much more approachable!

**Comment by stkent** [comment]
I believe this is now ripe for review again!

**Comment by jtigger** [comment]
I meant to signal 4 days ago that my folks were in town and I'd be far less responsive. :-/  So much for advanced warning.

I apologize for any inconvenience I've caused seemingly sitting on PRs, here.  Will get to these later today or tomorrow morning, the latest.

**Comment by stkent** [comment]
@jtigger absolutely no worries; this PR in particular has been through the do-not-merge/ready-for-merge cycle several times over!

**Comment by jtigger** [comment]
We'll be making little adjustments as we talk through some of our wider-margined scoring.  In the meantime, let's merge this in!  Woohoo!!

**Pull request merged**
