### PR TITLE
Pangram: build.gradle is empty

### LINKED ISSUE #79: Pangram: build.gradle is empty
The build.gradle for the pangram exercise is empty.

### PR DESCRIPTION
**Pull request by blemale**
* Provide a valid build.gradle for pangram exercise
* Close #79

### CODE REVIEW

**Comment by jtigger** [comment]
@blemale, thanks for the submission.  We inadvertently removed these for all projects.  We're going to revert that change, addressing this issue.

Apologies for any inconvenience.

**Comment by kytrinyx** [comment]
Deploying the fix now.

**Comment by kytrinyx** [comment]
Oh, wait. It's not reverted yet. Hold that thought :)

**Comment by jtigger** [comment]
almost there.  I'm doing due diligence, here.

**Comment by jtigger** [comment]
Done.  When you're ready, @kytrinyx, green light to deploy.

**Comment by kytrinyx** [comment]
On it. Thanks!

**Pull request closed without merging**
