### PR TITLE
Issue #261: Bring phone-number into compliance with canonical data

### PR DESCRIPTION
**Pull request by FridaTveit**
Added tests for cases we hadn't covered and changed example implementation to work in those cases. This should solve issue #261 .

### CODE REVIEW

**Comment by stkent** [comment]
This looks good to me! I notice that the final three tests are not included in the canonical data - are we ok with leaving these additional tests in the suite? (Note that they also increase the API surface of the implemented class).

**Comment by FridaTveit** [comment]
Yes, I did notice and wonder about that. I don't know why they were originally introduced so I didn't want to remove them without checking. I don't mind them being there, they don't add too much difficulty to the exercise and they make it a bit more interesting. @jtigger, @matthewmorgan do you think they should be there?

**Comment by jtigger** [comment]
_(Sorry for the delay, I missed the @-mention.)_

While they are interesting, I agree, they seem to fall outside the intended scope of the exercise.  The description even establishes _why_ we're scrubbing the phone number: "_... so that they can be sent SMS messages._"  That one phrase makes the `.pretty()` and `.getAreaCode()` seem like they're just hanging out for no apparent reason.

I look at it from the practitioner's point of view and pretend I'm a designer (that last part takes _a lot_ of imagination).  I ask, "how's does this exercise make the practitioner _feel_?"  Cohesion of problem (and therefore effort) makes me feel like I'm solving a whole problem; the lack thereof makes me feel like I'm being asked to do busywork.

**Comment by FridaTveit** [comment]
Okay, that makes sense. I'll remove those tests then :)

**Comment by stkent** [comment]
Thanks for weighing in, @jtigger, and for the follow-up changes, @FridaTveit! LGTM :)

**Pull request merged**
