### PR TITLE
Javaeeeee

### PR DESCRIPTION
**Pull request by javaeeeee**
Added Series exercise to Java track; branch javaeeeee.

### CODE REVIEW

**Comment by kotp** [comment]
hehe, was wondering why this issue was both open and closed... Schroedingers Pull Request.

You don't need to close a PR to update it, you can force push on the branch to update, or just commit again, until time to squash the commits.

**Comment by javaeeeee** [comment]
Hello Victor,

Sorry for the mess, it was my first pull request. Learning how things are
done. Should I open new requests if I add another problem to the roster or
I need just to push?

Thanks in advance,

Dmitry

**Comment by kotp** [comment]
Not a problem, for sure.  Just a familiarity thing, likely.

If the problem is closely related to the pull request, then there is likely no reason to create a new pull request.  There may be reason to not squash the commit, though, to keep it separated within that PR.

If the problem is unrelated, and more than "trivial" then a new pull request.

And, for sure, glad to see you here creating the pull requests.  The alternative is that you aren't here helping out, and that would be sad!

We are here if you have questions... don't be shy, it can help those here and that come after you.

**Comment by javaeeeee** [comment]
Thank you, Victor, for your response.

**Pull request closed without merging**
