### PR TITLE
Fix issue with jarfile

### PR DESCRIPTION
**Pull request by matthewmorgan**
A jarfile in the acronym directory was crashing the API😳

### CODE REVIEW

**Comment by jtigger** [comment]
At the end of the build, Travis says:

```
-> config.json does not include [gradle].
```

This means that the `gradle` directory is unexpected.  Kill that whole directory.  The only Gradle file that should be committed in an exercise is `build.gradle`.

I'm not sure how we got this far without having `gradle` in the `.gitignore` but it ought to be there to prevent such a situation.

@matthewmorgan signal me if you have other questions (I'll check email in the morning; I'm on Pacific time).

**Comment by matthewmorgan** [comment]
OK thanks @jtigger .  I also added `idea/` and `gradle/` to the "ignore" block in `config.json`.

There is still no `acronym` directory in `xjava/`.  That can't be OK.

**Comment by kytrinyx** [comment]
Shouldn't it be in `xjava/exercises/acronym`?

**Comment by matthewmorgan** [comment]
Well, it is, but all the older exercises (including `pangram`, which I submitted) have a folder in `xjava/` also, which looks like, among other things, compiled `.class` files.

There is no such folder for `acronym`, and I'm not sure how to produce it.  I must be missing a step.

**Comment by kytrinyx** [comment]
I don't have all those directories in my xjava.

**Comment by kytrinyx** [comment]
```
xjava $ ls -1
LICENSE
README.md
SETUP.md
bin
config.json
docs
exercises
```

**Comment by matthewmorgan** [comment]
Yep...I see that my fork is an amalgam of the old structure and the new...let me see if I can clean that up.

**Comment by matthewmorgan** [comment]
OK, that's done. Seems like things are OK but I would be happier if there were more eyes on it!

**Comment by jtigger** [comment]
I wish I could be more available right now; we're doing our big push for our move (just bought a house), this weekend.

Sounds like we could stand to do a google hangout together, Matthew.

I'll email you when I get up tomorrow.  I might have some time and in the very early morning (I'm on pacific time).

**Comment by matthewmorgan** [comment]
@jtigger I'm tied up today from ~9:30AM ET to 3:30 ET.  I don't know if that's compatible with your schedule or not, but if it is, let's talk.  Thanks!

**Comment by jtigger** [comment]
I'll be available tomorrow from 7a-9a, PT....  could that work? :)

----
(dictation taken by Thumba Leena)

**Comment by matthewmorgan** [comment]
I'm at work at that time...looks like today is not going to be good.

I hate to put it off this long, but unless sometime sort of 5p-9p ET works for you in the next couple of days (W/Th?), I'm working from home Monday with no conflicts currently.

**Comment by jtigger** [comment]
:) We'll figure this out... 

Normally, I could make arrangements to do something between 5p-9p, but I've already booked this week (all family stuff).

Meanwhile, to get this PR unstuck...

* the commit looks good to me. With one check (described below), I think you could roll with this.
 * There's a minor nip/tuck with the `config.json`.  Technically, there will never be a `gradle` or `.idea` directory in any of the exercises (especially given that both are git-ignored, now); so you can safely remove those from the ignored list in the `config.json` file.
* the check would be to test fetching this exercise through the CLI pointed at your local install of x-api.  (Check out step 2 in the [README.md](https://github.com/exercism/xjava#doing-the-commit-dance)).  Note that that step works only if you've done the [setup described further up](https://github.com/exercism/xjava#getting-setup).

If you can successfully fetch the exercise through the CLI, locally, you can confidently merge.

I hope this helps.  I'm looking forward to connecting up (soon!).

**Comment by matthewmorgan** [comment]
Hi John,  I tried to install the app locally but had a hell of a time with my Ruby install.  I had some conflicts with multiple versions that I wasn't able to resolve, so admit that I don't have a local install.  I can try again this weekend.

**Comment by jtigger** [comment]
Gotcha.

If I have some time in the morning, this week, I'll pull down your PR and
try it myself.  If I confirm, I'll let you know.

**Comment by matthewmorgan** [comment]
@jtigger made that change to config.json --let me know what you think when you get a chance.  Thanks!

**Comment by kytrinyx** [comment]
Is there any chance that this can be merged soon? I have to do manual work to remove acronym every time I deploy the x-api, which is starting to get a bit tedious. It also means that any new fixes (e.g. the docs changes from Trevor Halvorsen) are not being deployed as well, because complicated reasons having to do with submodules.

**Comment by matthewmorgan** [comment]
I think it's ready to merge but John was going to help me review it
locally.

We could merge it and find a different pr to study on.

**Comment by matthewmorgan** [comment]
@jtigger?  If you're comfortable merging this it sounds like we're holding up the show.  If you have no objections, that is.

**Comment by jtigger** [comment]
thumbs up!

----
(dictation taken by Thumba Leena)

**Comment by matthewmorgan** [comment]
Thanks!

**Comment by jtigger** [comment]
Thank you!

**Comment by kytrinyx** [comment]
Thanks y'all!

**Pull request merged**
