### PR TITLE
Journey builds trackler

### PR DESCRIPTION
**Pull request by jtigger**

### CODE REVIEW

**Comment by jtigger** [comment]
This fixes the build.  I meant to submit this *before* merging in the last two PRs...

**Comment by jtigger** [comment]
Did a code review with @matthewmorgan, yesterday.

Going to merge this in because the build is broken, subsequent PRs appear to fail, and this fixes it.

**Comment by matthewmorgan** [comment]
@jtigger thanks!  I got sidetracked yesterday.

**Comment by jtigger** [comment]
No worries, @matthewmorgan, I really appreciate you taking the time to do the review!  The rest is just mechanics.  I've fully drunk the Kool-Aid: broken builds are bad. :)

**Pull request merged**
