### PR TITLE
Add nth-prime exercise

### PR DESCRIPTION
**Pull request by winterchord**
Tests and example implementation based on the ruby exercise.

Completes a task for https://github.com/exercism/xjava/issues/3.

### CODE REVIEW

**Comment by jtigger** [comment]
Hey @winterchord, merging your previous PR created a merge conflict.  Would you mind doing a quite rebase?

Thanks for knocking these out. :)

**Comment by winterchord** [comment]
Will do when I get to my personal laptop.

**Comment by winterchord** [comment]
@jtigger Rebased and force pushed as requested.

**Comment by jtigger** [comment]
Thank you, sir.

**Pull request merged**
