### PR TITLE
rna-transcription: make object-based and add starter implementation

### PR DESCRIPTION
**Pull request by FridaTveit**
Changed rna-transcription to have an object based implementation (see issue #177) and added starter implementation as it is currently the second exercise in the new ordering (see issue #178).

### CODE REVIEW

**Comment by stkent** [comment]
Looks good! I'm not sure whether I prefer returning `null` vs throwing an unimplemented exception in the stubbed implementation - I feel like `null` could in general lead to a confusing error message when the tests are first run, and that the thrown exception route gives us more control over that messaging and experience. What do you think, Frida? I don't feel particularly strongly either way so I'm happy to go with whatever you decide, just let me know :)

**Comment by FridaTveit** [comment]
I didn't think about that, thanks for mentioning it! :) An exception is probably better. Do you think `UnsupportedOperationException` with message "Method has not been implemented yet" would be okay?

**Comment by stkent** [comment]
@FridaTveit that exception type sounds good to me, and to [others](http://stackoverflow.com/questions/829136/what-is-the-standard-exception-to-throw-in-java-for-not-supported-implemented-op)!

**Comment by stkent** [comment]
Thanks, @FridaTveit!

**Pull request merged**
