### PR TITLE
difference-of-squares: add to track

### PR DESCRIPTION
**Pull request by stkent**
Test data from https://github.com/exercism/x-common/blob/master/exercises/difference-of-squares/canonical-data.json

### CODE REVIEW

**Comment by stkent** [comment]
Going to overwrite with some tweaks shortly.

**Comment by stkent** [comment]
Should be good for review now.

**Comment by stkent** [comment]
Thank you, @jtigger! I see that in the past you have removed some exercise implementations from the Java track; is there a list somewhere of the exercises we _would_ want to add? Just trying to avoid implementing a problem that's not suitable for the track. Cheers!

**Comment by jtigger** [comment]
That is an excellent question, @stkent.

Here's a list of exercises well sorted: by number of languages already implemented.  All other factors being equal, I consider these high value because it allows the programmer to compare across languages:
http://exercism.io/languages/java/todo


@exercism/java, any wished for exercises in Java?

**Comment by stkent** [comment]
Ah, awesome, that's the list I had previously been referencing :) Hoping to tackle Queen Attack later today.

**Comment by jtigger** [comment]
Swwet!  Have fun, @stkent.  Appreciate all your help, sir.

**Pull request merged**
