### PR TITLE
Fixes #420

### LINKED ISSUE #420: nth-prime: simplify example implementation
In the function `isPrime` in `PrimeCalculator.java` the code:
```
    if (divisible) {
       return false;
    }

    return true;
```
can be changed to:
```
    return !divisible
```

### PR DESCRIPTION
**Pull request by ajayboseac**
nth-prime: simplify example implementation

### CODE REVIEW

**Comment by ajayboseac** [comment]
I am not able to figure out why the CI checks are failing. Can someone help ?

**Comment by FridaTveit** [comment]
Sorry, I'm not sure either. I tried restarting it but that didn't help. @jtigger @stkent any ideas?

**Comment by stkent** [comment]
No idea, sorry!

**Comment by jtigger** [comment]
On it.

**Comment by jtigger** [comment]
gak.  Not sure of the root cause, but I see that the latest version of Trackler is not playing well with the corresponding version of x-api.  I'm still digging...

**Comment by jtigger** [comment]
Found it... I'll submit a PR and explain there what the defect was.

**Comment by jtigger** [comment]
See #431 for details.  I'll keep an eye on it.

**Comment by jtigger** [comment]
I didn't see this PR's build automatically kick.  I wonder if that had anything to do with the fact that it's based of `master` and not a separate branch.  Does anyone know the deets on how that works in GitHub?

p.s. I manually rekicked the build, hoping it would incorporate #431.

**Comment by stkent** [comment]
Thanks, @jtigger!

And thanks, @ajayboseac, change looks great; merging!

**Comment by ajayboseac** [comment]
Thanks  @jtigger and @stkent

**Pull request merged**
