### PR TITLE
fix broken links for Tests.md

### PR DESCRIPTION
**Pull request by michaelkunc**

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@michaelkunc thanks for doing this, it doesn't look like the new links are pointing at the right places though.  FWIW I went back and checked the ones merged in PR #88 and they're not working.  I'm guessing something has moved?  @jtigger -- can you comment on this?

**Comment by jtigger** [comment]
they moved again?!? grrrr.  I'll take a look in the morning.

----
(dictation taken by Thumba Leena)

**Comment by jtigger** [comment]
Yup, the images didn't make it over from the help repo.

**Comment by jtigger** [comment]
PR submitted: exercism/exercism.io#2769

**Comment by jtigger** [comment]
@michaelkunc would you mind adjusting the paths to line up with those in that PR?  There was "prior art" where the same kind of files were put there; we should fall in line.

**Comment by matthewmorgan** [comment]
All set-- I added the images to `docs/img` and merged.

**Comment by matthewmorgan** [comment]
@michaelkunc @jtigger Thanks!

**Pull request closed without merging**
