### PR TITLE
Added binary search tree exercise to the Java track

### PR DESCRIPTION
**Pull request by javaeeeee**
Added binary search tree assignment to the Java track.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@javaeeeee thanks for another PR!  I noticed you've been contributing a lot to exercism lately and it's appreciated!

Can I ask from where you got the idea for the API your solution?  There is no `config.json` in x-common for this one-- did you pattern it after the Scala version by chance?

I particularly appreciate the fact that you're returning an unmodifiable copy of the list.  Well done.

**Comment by javaeeeee** [comment]
Hello Matthew,

Thank you for reviewing my PR. Currently, I am doing the JavaScript track
and try to add the missing exercises to the Java track. Just changed the
test that checks the addition of many nodes by printing them level by
level. The idea came from HackerRank.

I'd like to take the Scala track later.

**Comment by matthewmorgan** [comment]
OK Dmitry,

When you're ready you'll need to merge master in here once more and resolve the merge conflicts.  if you need help please don't hesitate to ask.

**Comment by javaeeeee** [comment]
Thank you. Managed to merge myself.

**Comment by matthewmorgan** [comment]
Wohoo!  Nice work mate!  Thanks again.

**Comment by javaeeeee** [comment]
Thank you. :)

**Pull request merged**
