### PR TITLE
Clock: add to track

### PR DESCRIPTION
**Pull request by FridaTveit**

### CODE REVIEW

**Comment by jtigger** [comment]
I suspect you're ready to go here?

When you're ready for a review, @FridaTveit, please either edit the title to read: "_exercise_: add to track" and/or hit that "No reviews — request one" link to the right.

**Comment by FridaTveit** [comment]
Oh okay, will do!

**Comment by matthewmorgan** [comment]
@FridaTveit we have merge conflicts introduced by merging some previous PRs.  Would you mind fixing them, or LMK and I can do it.  Thanks!

**Comment by FridaTveit** [comment]
Will do! :)

**Comment by matthewmorgan** [comment]
Go @FridaTveit !

**Pull request merged**
