### PR TITLE
scrabble-score: replace illegal word

### PR DESCRIPTION
**Pull request by kytrinyx**
multibillionaire can't be played as a word in a real scrabble game. See https://github.com/exercism/x-common/issues/86

### CODE REVIEW

**Comment by jtigger** [comment]
Dig the replacement word. :smile:

I ran the tests locally (since that isn't yet happening in CI); ran green, here.

**Comment by kytrinyx** [comment]
Thanks! I don't have the java tests running locally. I really should get on that...

**Comment by jtigger** [comment]
You shouldn't have to (beyond just installing gradle and running the build).  I suspect you've got higher priorities. ;)

After I finish with the getting started documentation, having a complete and automated build seems to be the next priority for the Java track.

I mentioned running the tests purely for documenting the fact that it happened.

**Comment by kytrinyx** [comment]
> I suspect you've got higher priorities

How did you guess? :)

> After I finish with the getting started documentation, having a complete and automated build seems to be the next priority for the Java track.

Yeah, that sounds like a good set of priorities.

**Pull request merged**
