### PR TITLE
Test for Robot name allows other characters for the first 2 characters

### PR DESCRIPTION
**Pull request by jmluy**
First 2 characters in test allows numbers, lowercased letters or underscores.

### CODE REVIEW

**Comment by kytrinyx** [comment]
This looks good to me, but I'll defer to @jtigger to merge.

Would you mind squashing the commits please? (Here's a quick guide in case it's helpful. It assumes that you have a git remote named `upstream` that points to the exercism/xjava repository )http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)

**Comment by kytrinyx** [comment]
One question--do we want a test that clarifies that lower-case names are not allowed?

**Comment by jmluy** [comment]
thanks, will check on squashing.

regarding the test, it's the test that's not accurate but we can have the test for lowercased names separately

**Comment by kytrinyx** [comment]
Yeah, the lowercase thing is a separate problem (if it's a problem at all). Thanks!

**Comment by jmluy** [comment]
Should it allow uppercased words? If it does, it might just need some more examples on the readme file or a clarification.

**Comment by kytrinyx** [comment]
I'm not sure I understand the question. At the moment the README implicitly suggests that the name should be all uppercase. I don't think there's any reason to allow lowercase letters.

**Comment by jtigger** [comment]
Hey y'all, I've been out-of-pocket for the past month.  I apologize for not being responsive, here.  Catching up now.

**Comment by jtigger** [comment]
@jmluy, thank you for the contribution!  Your implementation is inline with how we're generally thinking about this problem (see exercism/exercism.io#2441).

In lieu of CI that runs the test against the example, I did so manually (tickling the example implementation to generate lowercase names, verifying that the assertion catches it).

(Always looking forward, I'd love to see a more telling test signal than...

```
RobotTest > hasName FAILED
    java.lang.AssertionError at RobotTest.java:33
```

... an aspect of making Exercism an exemplar would be showing how test output makes plain the exact failure (an important aspect of "good" test systems)...

```
Generated robot name was invalid; it did not match the pattern [A-Z]{2}[0-9]{3}.
```

...)

**Comment by kytrinyx** [comment]
Reading error messages is one of those habits that I've struggled to impart to newer developers. I would love it if exercism helped encourage better error-reading skills (since that seems like it's a pre-requisite for improved error-writing skills...)

**Pull request merged**
