### PR TITLE
A (partial) fix for the issue #2670

### PR DESCRIPTION
**Pull request by samilaine**
Instructions on how to get Exercism and Eclipse play together have been asked a few times. Since this seems to be something that might deserve more than just a(nother) post to the thread describing the issue, an actual pull request follows.

### CODE REVIEW

**Comment by kytrinyx** [comment]
:heart: thank you!

I'll leave this for the track maintainers to review.

@jtigger @matthewmorgan this is failing with the message _The command "bin/journey-test.sh" exited with 1._ That seems odd for a documentation fix. Any ideas?

**Comment by jtigger** [comment]
That failure is no good; I'll look into this.  Thanks, @samilaine for the contribution!

**Comment by jtigger** [comment]
Ah... it's failing on the x-api install — it presumes that the right version of ruby is installed and it's not on Travis-CI.  I've got some morning responsibilities to handle and will fix this ASAP.

**Comment by jtigger** [comment]
Okay. Fixed the build on master.  @samilaine would you please rebase your PR?

**Comment by samilaine** [comment]
I believe a rebase on the fork is now done.

**Comment by jtigger** [comment]
Did you fetch from the exercism/xjava remote and rebase from that remote's master?

Either way, we appreciate your support -- I've merged this PR knowing full well the build failure had nothing to do with this PR.

**Comment by samilaine** [comment]
Being more comfortable using git in any other context than GitHub, there is more than zero chance of me doing something wrong. Feedback and instructions are most welcome, what I did is below:

```
git clone git@github.com:samilaine/xjava.git
git remote add upstream https://github.com/exercism/xjava.git
git fetch upstream
git rebase upstream/master
git rebase upstream/master
git push -f origin master
```

**Pull request merged**
