### PR TITLE
Add test for same word in anagram.

### PR DESCRIPTION
**Pull request by jmluy**
Existing test (testIdenticalWordIsNotAnagram) for words only check that it contains the anagram but not that it shouldn't contain the same word.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Can we change the assertion on `testIdenticalWordIsNotAnagram` so that it asserts the full list of expected results, rather than just that it contains the expected anagram instead of adding a new test?

**Comment by jmluy** [comment]
Updated to compare list containing the only anagram.

**Comment by kytrinyx** [comment]
I like this--it's a bit simpler than adding an extra test. Thanks!

**Comment by kytrinyx** [comment]
Merged in 04a082121af34013d0a30e4a50d3d57202734876

**Pull request closed without merging**
