### PR TITLE
dibs: I will implement exercise beer-song

### PR DESCRIPTION
**Pull request by jeseekia**

### CODE REVIEW

**Comment by matthewmorgan** [comment]
Awesome!  I think 'dibs' should be submitted as an issue, though, rather than a pull request.

Let me know if I can be of any help.

**Comment by jeseekia** [comment]
Thanks for the tip. That would have been a bit simpler. I specifically followed the directions from the contributing guide which says to open a work in progress pull request to claim an exercise https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track . Is this document out of date? I am using that as well as this https://github.com/exercism/xjava#contributing-guide in order to get through this first contribution.

**Comment by matthewmorgan** [comment]
I'm probably out of date!  Sorry about that.

Anyway, the offer to help stands if you need anything.

On Wed, May 25, 2016 at 9:41 AM, Jeseekia Vaughn <notifications@github.com>
wrote:

> Thanks for the tip. That would have been a bit simpler. I specifically
> followed the directions from the contributing guide which says to open a
> work in progress pull request to claim an exercise
> https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track
> . Is this document out of date? I am using that as well as this
> https://github.com/exercism/xjava#contributing-guide in order to get
> through this first contribution.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xjava/pull/115#issuecomment-221579482>
>



-- 
Matt Morgan
+1 734 904 9328

**Comment by kytrinyx** [comment]
I prefer to have these as pull requests, as it ends up generating less noise. People can update the pull request with their implementation of the exercise, and there is no risk of having unclosed, out of date issues.

**Comment by jeseekia** [comment]
Hello, again! I am almost ready to update this pull request. I have gotten to [running the build](https://github.com/exercism/xjava#running-the-build) and get a successful build on all of the exercises including this new one.
Next, should I delete the solution from the exercises/beer-song/src/main/ and leave the solution in the exercises/beer-song/src/example/ ?

**Comment by matthewmorgan** [comment]
Yes, your exercise solution belongs in `exercises/beer-song/src/example/`.  If you want to push your PR I can have a look (tomorrow!)

**Comment by jeseekia** [comment]
It looks like there is an issue with the config.json. Is that something I should have changed? Perhaps I missed a step. Also, my rebases are not really updating appropriately. Any resources you recommend for getting help on squashing those commits? The empty commit isn't getting treated the same as the regular commits when I try to rebase.

**Comment by kytrinyx** [comment]
> It looks like there is an issue with the config.json.

Yepp, if you open up the config.json and find the `problems` key, you'll need to add `beer-song` to that array. The array lists exercises roughly in order of difficulty. Or rather, we use the order of that array to decide what "next" means in terms of delivering exercises to people.

> For reference, I attempted this to squash my 2 commits and ended up with more commits

I think this is what people refer to as getting themselves "up git creek" :) I'll help you sort this out!

First: do you have an upstream? What does `git remote -v` output?

**Comment by matthewmorgan** [comment]
The example solution is quite elegant.  Nice work!

@jeseekia @kytrinyx when I add the `beer-song` exercise to `config.json` things work as expected.  I suspect that's what's holding up the build.

One point though: though there is no `beer-song.json` file that defines this as a standard, the ES, JS, and Ruby tracks all expect an additional newline character between verses.  May I suggest adding that in the example and testing for it?  

Also, the other test suites that I've looked at do test the whole song, with other tracks providing a separate method for 'singing' the whole song, as opposed to `verse(n)` or `verses(n, m)`.

Again, I'm happy to help, although I'm headed out of town for a couple of days tomorrow, no internet for a 'til I return.

**Comment by jeseekia** [comment]
@kytrinyx I get:
origin	https://github.com/jeseekia/xjava.git (fetch)
origin	https://github.com/jeseekia/xjava.git (push)

**Comment by jeseekia** [comment]
@matthewmorgan My internet crapped out last night. Sorry I didn’t get to reply sooner. Thank you. I modeled the exercise test suite after C#. I agree that it would definitely be more thorough to add the test for the entire song. I am adding the additional line break at the end of verses and the test case for the entire song. Perhaps you'll be able to take a look at that next week, after I've pushed the new commits and figured out how to properly squash them!

**Comment by kytrinyx** [comment]
Hi @jeseekia! Sorry I didn't get to this earlier. Here's how I would do the rebase:

```
git remote add upstream https://github.com/exercism/xjava.git
git fetch upstream
git rebase upstream master
```

Then take a look at the history and figure out how many commits you have. If it's 4 then you can do an interactive rebase:

```
git rebase -i HEAD~4
```

And then you edit all but the last commit to say "squash" instead of "pick".

**Comment by matthewmorgan** [comment]
@jeseekia there are a couple more changes that need to be made, and one of them escaped my notice the last time, sorry:

1. add 'beer-song' to `exercises/settings.gradle` (this is the one I missed)
2. in the final test: there is a final newline missing
3. your example code will need a method for singing the whole song, to call during that final test.  

I also wanted to suggest an alternative way to squash your commits.  If you don't need to groom the individual commits, you can just use:

```
git reset --soft <hash-of-last-commit-in-master>
git commit -am 'Add a single commit message to describe your PR'
```

I'm back and available, so please let me know if you need anything at all.

**Comment by jeseekia** [comment]
@matthewmorgan thanks so much! I'm learning a lot from this process. I will be working on setting up the dev environment on my work computer as well so it doesn't take so long to get updates done.

**Comment by matthewmorgan** [comment]
No worries, I should have added, after you do that last commit, you'll need to force-push your branch.  I've modified the instructions above.

**Comment by matthewmorgan** [comment]
@jeseekia Looking good!  Are you ready to squash the commits here?  Again, let me know if I can help.

**Comment by jeseekia** [comment]
ONE COMMIT! :fireworks:

**Comment by matthewmorgan** [comment]
Awesome!  I have been buried the last couple of days but I'm hoping to pull your changes and, if everything looks goods, merge this tonight.  👍

**Comment by jtigger** [comment]
if not tonight, tomorrow morning! ;)

**Comment by matthewmorgan** [comment]
Nice work!  Sorry for the delay in getting it merged, but we appreciate your contribution.

**Comment by jeseekia** [comment]
@matthewmorgan thanks so much! I will be back for more!

**Pull request merged**
